# Default initial positions for dual_hiwin's ros2_control fake system

initial_positions:
  big_joint_1: 0
  big_joint_2: 0
  big_joint_3: 0
  big_joint_4: 0
  big_joint_5: 0
  big_joint_6: 0
  small_joint_1: 0
  small_joint_2: 0
  small_joint_3: 0
  small_joint_4: 0
  small_joint_5: 0
  small_joint_6: 0