# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    big_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    small_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

big_controller:
  ros__parameters:
    joints:
      - big_joint_1
      - big_joint_2
      - big_joint_3
      - big_joint_4
      - big_joint_5
      - big_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
small_controller:
  ros__parameters:
    joints:
      - small_joint_1
      - small_joint_2
      - small_joint_3
      - small_joint_4
      - small_joint_5
      - small_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity