# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
#   # 👇 1. 把命名空間寫在控制器名稱裡
#   controller_names:
#     - small_arm/small_arm_controller
#     - big_arm/big_arm_controller

#   # 👇 2. 對應的控制器設定
#   small_arm/small_arm_controller:
#     type: FollowJointTrajectory
#     action_ns: follow_joint_trajectory  # 保持相對路徑，MoveIt 會自動接成 /small_arm/small_arm_controller/follow_joint_trajectory
#     default: true
#     joints:
#       - small_joint_1
#       - small_joint_2
#       - small_joint_3
#       - small_joint_4
#       - small_joint_5
#       - small_joint_6

#   big_arm/big_arm_controller:
#     type: FollowJointTrajectory
#     action_ns: follow_joint_trajectory
#     default: true
#     joints:
#       - big_joint_1
#       - big_joint_2
#       - big_joint_3
#       - big_joint_4
#       - big_joint_5
#       - big_joint_6


moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  # 控制器名稱 = 手臂 namespace + 控制器名（joint_trajectory_controller）
  # MoveIt 會組成 action 路徑：/<下面的名字>/<action_ns>
  controller_names:
    - small_arm/joint_trajectory_controller
    - big_arm/joint_trajectory_controller

  # B 臂（small / RA605）
  # -> action: /small_arm/joint_trajectory_controller/follow_joint_trajectory
  small_arm/joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - small_joint_1
      - small_joint_2
      - small_joint_3
      - small_joint_4
      - small_joint_5
      - small_joint_6

  # A 臂（big / RA610）
  # -> action: /big_arm/joint_trajectory_controller/follow_joint_trajectory
  big_arm/joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - big_joint_1
      - big_joint_2
      - big_joint_3
      - big_joint_4
      - big_joint_5
      - big_joint_6