gpio_controller:
  ros__parameters:
    type: hiwin_controllers/GPIOController
    update_rate: 20  # Hz

    gpios:
      - system
      - digital
    command_interfaces:
      system:
        interfaces:
          - watchdog
          - reset_safety_rly
          - reset_driver
      digital:
        interfaces:
          - DO1_1
          - DO1_2
          - DO1_3
          - DO1_4
          - DO1_5
          - DO1_6
          - DO1_7
          - DO1_8
          - DO2_1
    state_interfaces:
      system:
        interfaces:
          - breaker
          - e_stop
          - e_stop2
          - fan_error
          - capacitor_error
          - clear_error_notify
          - shutdown_notify
      digital:
        interfaces:
          - DI1_1
          - DI1_2
          - DI1_3
          - DI1_4
          - DI1_5
          - DI1_6
          - DI1_7
          - DI1_8
          - DI2_1
