controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    reset_fault_controller:
      type: hiwin_controllers/ResetFaultController

joint_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    closed_loop: true
    interpolation_method: "splines"

reset_fault_controller:
  ros__parameters:
    update_rate: 100
    trajectory_action_server: "/joint_trajectory_controller/follow_joint_trajectory"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - reset_fault
    state_interfaces:
      - position
